/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sl.tool;

import com.sl.patterns.Patterns;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class PatternsTest {
    @Test void appHasAGreeting() {
        Patterns classUnderTest = new Patterns();
        assertNotNull(classUnderTest.getGreeting(), "tool should have a greeting");
    }
}
