/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sl.batch;

public class Batch {
    public String getGreeting() {
        return "Hello World - Batch!";
    }

    public static void main(String[] args) {
        System.out.println(new Batch().getGreeting());
    }
}
