/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sl.patterns;

import javax.tools.Tool;

public class Patterns {
    public String getGreeting() {
        return "Hello World - Patterns!";
    }

    public static void main(String[] args) {
        System.out.println(new Patterns().getGreeting());
    }
}
