/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sl.tool;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ToolTest {
    @Test void appHasAGreeting() {
        //Tool classUnderTest = new Tool();
        //assertNotNull(classUnderTest.getGreeting(), "tool should have a greeting");
    }
}
