/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sl.batch;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BatchTest {
    @Test void appHasAGreeting() {
        Batch classUnderTest = new Batch();
        assertNotNull(classUnderTest.getGreeting(), "tool should have a greeting");
    }
}
