/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sl.config;

import com.sl.config.dao.ConfigJdbcDAO;
import com.sl.config.dao.PersonDAO;
import com.sl.config.model.Person;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.*;
import java.util.List;

public class Config {
    public String getGreeting() {
        return "Hello World - Config!";
    }

    public static void main(String[] args) {
        //System.out.println(new Config().getGreeting());
        //getDB(1);

        //step 2
//        System.out.println("Hello, spring");
//        ApplicationContext applicationContext = new AnnotationConfigApplicationContext(AppConfig.class);
//        ConfigService service = applicationContext.getBean("configService", ConfigService.class);
//        System.out.println(service.list());
        testPersonDAO();
    }

    public static void testPersonDAO() {

        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class);

        PersonDAO personDAO = context.getBean(PersonDAO.class);

        System.out.println("List of person is:");

        for (Person p : personDAO.getAllPersons()) {
            System.out.println(p);
        }

        System.out.println("\nGet person with ID 3");

        Person personById = personDAO.getPersonById(3L).get(0);
        System.out.println(personById);

        System.out.println("\nCreating person: ");
        Person person = new Person(4L, 36, "Sergey", "Emets");
        System.out.println(person);
        personDAO.createPerson(person);
        System.out.println("\nList of person is:");

        for (Person p : personDAO.getAllPersons()) {
            System.out.println(p);
        }

        //System.out.println("\nDeleting person with ID 2");
        //personDAO.deletePerson(personById);

        System.out.println("\nUpdate person with ID 4");

        Person pperson = personDAO.getPersonById(4L).get(0);
        pperson.setLastName("CHANGED");
        personDAO.updatePerson(pperson);

        System.out.println("\nList of person is:");
        for (Person p : personDAO.getAllPersons()) {
            System.out.println(p);
        }

        context.close();
    }

    public static void test() {
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con= DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/project1?useTimezone=true&serverTimezone=UTC&useSSL=false","root","admin");
            //here sonoo is database name, root is username and password
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from config");
            while(rs.next())
                System.out.println(rs.getInt(1)+"  "+rs.getString(2)+"  "+rs.getString(3));

            con.close();
        }catch(Exception e){ System.out.println(e);}
    }

    public static String getDB(int id) {
        // ref: http://tutorials.jenkov.com/jdbc/preparedstatement.html
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection= DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/project1?useTimezone=true&serverTimezone=UTC&useSSL=false","root","admin");

            String sql = "select * from config where id=?";

            PreparedStatement preparedStatement =
                    connection.prepareStatement(sql);

            preparedStatement.setLong(1, id);

            ResultSet rs = preparedStatement.executeQuery();

            String db = null;
            if (rs.next()) {
                db = rs.getString(3);
            }

            connection.close();

            return db;

        }catch(Exception e){ System.out.println(e);}

        return null;

    }

    public static void getConfigList() {

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection= DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/project1?useTimezone=true&serverTimezone=UTC&useSSL=false","root","admin");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }


        JdbcTemplate jdbcTemplate = new JdbcTemplate();
        ConfigJdbcDAO configJdbcDAO = new ConfigJdbcDAO(jdbcTemplate);

        List<com.sl.config.model.Config> configs = configJdbcDAO.list();

    }
}
