/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sl.tool;

public class Tool {
    public String getGreeting() {
        return "Hello World - Tool!";
    }

    public static void main(String[] args) {
        System.out.println(new Tool().getGreeting());
    }
}
